function r = homography_degen(X)
        
x1 = X(1:3,:);    % Extract x1 and x2 from x
x2 = X(4:6,:);

r = ...
    iscolinear(x1(:,1),x1(:,2),x1(:,3)) | ...
    iscolinear(x1(:,1),x1(:,2),x1(:,4)) | ...
    iscolinear(x1(:,1),x1(:,3),x1(:,4)) | ...
    iscolinear(x1(:,2),x1(:,3),x1(:,4)) | ...
    iscolinear(x2(:,1),x2(:,2),x2(:,3)) | ...
    iscolinear(x2(:,1),x2(:,2),x2(:,4)) | ...
    iscolinear(x2(:,1),x2(:,3),x2(:,4)) | ...
    iscolinear(x2(:,2),x2(:,3),x2(:,4));

end


% function r = homography_degen(X)
%         
% r =  any(pdist(X(1:2,:)') < eps);
% 
% r = r + any(pdist(X(3:4,:)') < eps);
% 
% end
